/**
 * GuidePage content exports
 */

export {
  CALCULATION_STEPS,
  FACTOR_DEFINITIONS,
  METRICS,
  PROBLEM_ELEMENTS,
  PROBLEM_EXAMPLE,
  PROBLEM_WRITING_TIPS,
  SOLUTION_COMPONENTS,
  SOLUTION_EXAMPLE,
  SOLUTION_PITFALLS,
} from './guidePageContent';
