/**
 * GuidePage content exports
 */

// Original exports
export {
  CALCULATION_STEPS,
  FACTOR_DEFINITIONS,
  METRICS,
  PROBLEM_ELEMENTS,
  PROBLEM_EXAMPLE,
  PROBLEM_WRITING_TIPS,
  SOLUTION_COMPONENTS,
  SOLUTION_EXAMPLE,
  SOLUTION_PITFALLS,
} from './guidePageContent';

// Transferred content from drawers
export {
  ASSESSMENT_METHODOLOGY,
  BUSINESS_CONTEXT,
  BUSINESS_PROBLEM,
  BUSINESS_SOLUTION,
  EVALUATION_CRITERIA,
  EVALUATION_PARAMETERS,
  GUIDE_PAGE_CONTENT,
  SAMPLE_TEST_CASES,
  SPECIFIC_EVALUATION_PARAMETERS,
  parameterGuidance,
} from './guidePageContent';
