/**
 * Embedding Storage Script
 *
 * Stores pre-generated embeddings from embedded_chunks.json into Supabase.
 * Reads from backend/datasets/out/embedded_chunks.json (generated by generate_embeddings.js)
 * or from backend/datasets/archives/embedded_chunks.json when run with `--archives`.
 *
 * Usage: node store_embeddings.js [embedded_chunks_path]
 * Default: datasets/out/embedded_chunks.json (use `--archives` to use datasets/archives/embedded_chunks.json)
 *
 * Uses centralized embedding configuration from backend/src/config/embedding.js
 */

import '#server/bootstrap.js';
import fs from 'fs';
import path from 'path';
import { createSupabaseClient } from '#database/supabase.client.js';
import { DATASETS_OUTPUT_DIR, DATASETS_ARCHIVES_DIR } from '#utils/datasetsUtils.js';
import { BACKEND_CONFIG } from '#config/backend.config.js';
import { isValidTextForEmbedding, isValidEmbedding } from '#config/embedding.js';
import { fileURLToPath } from 'url';

// Determine whether we should target the archive dataset.
// CLI flags take precedence but falling back to environment via BACKEND_CONFIG
const useArchive =
  process.argv.includes('--archives') ||
  process.argv.includes('--archive') ||
  (BACKEND_CONFIG.db && BACKEND_CONFIG.db.tables.documents === 'documents_archives');
const DRY_RUN = process.argv.includes('--dry-run') || !BACKEND_CONFIG.supabase.serviceKey;

let supabase = null;
if (!DRY_RUN) {
  supabase = createSupabaseClient();
}

/**
 * Load previously generated embedded chunks
 * @param {string} embeddedChunksPath - Path to embedded_chunks.json
 * @returns {Array} Array of embedded chunk objects
 * @throws {Error} If file not found or invalid JSON
 */
export function loadEmbeddedChunks(embeddedChunksPath) {
  if (!fs.existsSync(embeddedChunksPath)) {
    throw new Error(`Embedded chunks file not found at ${embeddedChunksPath}`);
  }

  try {
    const fileContent = fs.readFileSync(embeddedChunksPath, 'utf-8');
    const chunks = JSON.parse(fileContent);

    if (!Array.isArray(chunks)) {
      throw new Error('Embedded chunks file must contain a JSON array');
    }

    console.log(`✓ Loaded ${chunks.length} embedded chunks from ${embeddedChunksPath}`);
    return chunks;
  } catch (error) {
    throw new Error(`Failed to load embedded chunks: ${error.message}`);
  }
}

/**
 * Store embedded chunks in Supabase documents table
 * @param {Array} embeddedChunks - Chunks with embedding vectors
 * @returns {Promise<number>} Number of documents successfully stored
 * @throws {Error} If storage fails after retries
 */
export async function storeInSupabase(embeddedChunks) {
  console.log(
    `\nStoring ${embeddedChunks.length} documents${DRY_RUN ? ' (dry-run -> local JSONL)' : ' in Supabase'}...`,
  );

  // Determine target table based on archives flag:
  // - If --archives (or --archive) is present: write archives embedded_chunks.json -> `documents` table
  // Determine target table and function names based on archive flag
  // Note: useArchive from CLI flag takes precedence over environment USE_DOCUMENTS_ARCHIVES_TABLE
  const effectiveUseArchive = useArchive;
  const dbConfig = {
    tables: {
      documents: effectiveUseArchive ? 'documents_archives' : 'documents',
    },
    functions: {
      truncate: effectiveUseArchive ? 'truncate_documents_archives' : 'truncate_documents',
    },
  };

  const targetTable = dbConfig.tables.documents;

  if (!DRY_RUN) {
    console.log('  Using SUPABASE_SERVICE_ROLE_KEY (required for RLS bypass)\n');
    console.log(`Truncating existing ${targetTable} table (clear previous run data)...`);

    try {
      if (targetTable === 'documents') {
        const { error: truncateError } = await supabase.rpc(dbConfig.functions.truncate);
        if (truncateError) {
          throw new Error(`Truncate failed: ${truncateError.message}`);
        }
      } else if (targetTable === 'documents_archives') {
        // Try RPC first (if available), otherwise delete all rows via service role
        const { error: truncateError } = await supabase.rpc(dbConfig.functions.truncate);
        if (truncateError) {
          console.log('  RPC truncate not available; using direct delete for ' + targetTable);
          const { error: delErr } = await supabase.from(targetTable).delete().neq('id', '');
          if (delErr) {
            throw new Error(`Failed to clear ${targetTable}: ${delErr.message}`);
          }
        }
      }

      console.log(`✓ ${targetTable} cleared.\n`);
    } catch (error) {
      console.error('✗ Table clear failed:', error.message);
      throw error;
    }
  } else {
    console.log('Dry-run mode: skipping table truncate/clear.\n');
  }

  const SUPABASE_BATCH_SIZE = 10;
  let totalStored = 0;
  let batchNum = 0;

  for (let i = 0; i < embeddedChunks.length; i += SUPABASE_BATCH_SIZE) {
    batchNum++;
    const batch = embeddedChunks.slice(i, Math.min(i + SUPABASE_BATCH_SIZE, embeddedChunks.length));
    const documentsToInsert = [];

    // Prepare documents for insertion
    for (const chunk of batch) {
      // Extract structured columns (no defaults - assume upstream normalization)
      const industryVal = chunk.metadata?.industry ?? null;
      const categoryVal = chunk.metadata?.category ?? null;
      const sourceVal = chunk.metadata?.source ?? null;

      // Build metadata object for JSONB
      const baseMeta = {
        chunk_id: chunk.id,
        source_row: chunk.source_row,
        chunk_index: chunk.chunk_index,
        chunk_type: (chunk.metadata && chunk.metadata.chunk_type) || 'primary',
        source_id: (chunk.metadata && chunk.metadata.source_id) || null,
        fields: (chunk.metadata && chunk.metadata.fields) || {},
        word_count: chunk.word_count,
        scale: (chunk.metadata && chunk.metadata.scale) || null,
        r_strategy: (chunk.metadata && chunk.metadata.r_strategy) || null,
        primary_material: (chunk.metadata && chunk.metadata.primary_material) || null,
        geographic_focus: (chunk.metadata && chunk.metadata.geographic_focus) || null,
      };

      // Doc-level document
      if (chunk.embeddings && chunk.embeddings.doc && isValidEmbedding(chunk.embeddings.doc)) {
        documentsToInsert.push({
          content: chunk.content,
          embedding: chunk.embeddings.doc,
          industry: industryVal,
          category: categoryVal,
          source: sourceVal,
          metadata: { ...baseMeta, field_name: 'doc' },
        });
      }

      // Field-level documents
      const fieldEmb = (chunk.embeddings && chunk.embeddings.fields) || {};
      for (const [fname, vec] of Object.entries(fieldEmb)) {
        if (!vec || !isValidEmbedding(vec)) continue;

        const fieldText =
          (chunk.metadata && chunk.metadata.fields && chunk.metadata.fields[fname]) || '';
        if (!isValidTextForEmbedding(fieldText)) continue;

        documentsToInsert.push({
          content: fieldText,
          embedding: vec,
          industry: industryVal,
          category: categoryVal,
          source: sourceVal,
          metadata: { ...baseMeta, field_name: fname },
        });
      }
    }

    if (documentsToInsert.length === 0) {
      console.log(`  Batch ${batchNum}: No valid documents (all embeddings invalid)`);
      continue;
    }

    // Insert batch with error handling
    if (DRY_RUN) {
      // Write to local JSONL for inspection
      const outPath = path.join(DATASETS_OUTPUT_DIR, 'stored_documents.jsonl');
      // ensure output directory exists when dry-run is writing locally
      const outDir = path.dirname(outPath);
      if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
      }
      try {
        for (const doc of documentsToInsert) {
          fs.appendFileSync(outPath, JSON.stringify(doc) + '\n', 'utf8');
        }
        totalStored += documentsToInsert.length;
        console.log(
          `  ✓ Batch ${batchNum}: Wrote ${documentsToInsert.length} documents to ${outPath}`,
        );
      } catch (error) {
        console.error(`  ✗ Batch ${batchNum}: Failed to write JSONL:`, error.message);
        throw error;
      }
    } else {
      try {
        const { data, error } = await supabase.from(targetTable).insert(documentsToInsert).select();

        if (error) {
          throw new Error(`Insert failed: ${error.message}`);
        }

        if (!Array.isArray(data)) {
          throw new Error('Unexpected response: data is not an array');
        }

        totalStored += data.length;
        console.log(
          `  ✓ Batch ${batchNum}: Inserted ${data.length} documents into ${targetTable} (sample ID: ${data[0]?.id || '(no id)'})`,
        );
      } catch (error) {
        console.error(`  ✗ Batch ${batchNum} failed:`, error.message);
        throw error;
      }
    }
  }

  console.log(`\n✓ Successfully stored ${totalStored} documents in Supabase\n`);
  return totalStored;
}

/**
 * Validate stored embeddings with test query
 * @private
 */
async function validateStorage() {
  console.log('\nValidating stored embeddings...');

  try {
    // Count total documents in the target table (dynamic based on archive flag)
    try {
      const { count, error: countErr } = await supabase
        .from(dbConfig.tables.documents)
        .select('id', { head: true, count: 'exact' });
      if (!countErr) {
        console.log(`  ✓ Total documents in ${dbConfig.tables.documents}: ${count}`);
      }
    } catch (e) {
      console.warn('  ⚠ Could not retrieve documents count:', e.message);
    }

    // Test vector search with a dummy embedding
    const testEmbedding = Array(1536).fill(0.1);
    const searchResult = await supabase.rpc(dbConfig.functions.match_documents, {
      query_embedding: testEmbedding,
      match_count: 1,
    });

    if (!searchResult.error) {
      console.log(`  ✓ Vector search function operational`);
      if (searchResult.data && searchResult.data.length > 0) {
        console.log(`  ✓ Search returned ${searchResult.data.length} result(s)`);
      }
    }
  } catch (error) {
    console.warn('  ⚠ Validation warning:', error.message);
  }
}

/**
 * Main execution pipeline
 * @async
 */
export async function main() {
  const embeddedChunksPath =
    process.argv[2] ||
    (useArchive
      ? path.join(DATASETS_ARCHIVES_DIR, 'embedded_chunks.json')
      : path.join(DATASETS_OUTPUT_DIR, 'embedded_chunks.json'));

  try {
    console.log('╔════════════════════════════════════════════════════════════════════╗');
    console.log('║  Embedding Storage Pipeline                                        ║');
    console.log('║  Circular Economy Business Auditor                                 ║');
    console.log('╚════════════════════════════════════════════════════════════════════╝\n');

    // Step 1: Load embedded chunks
    const embeddedChunks = loadEmbeddedChunks(embeddedChunksPath);

    // Step 2: Store in Supabase
    const storedCount = await storeInSupabase(embeddedChunks);

    // Step 3: Validate storage (production only)
    if (!DRY_RUN) {
      await validateStorage();
    } else {
      console.log('Dry-run mode: skipped Supabase validation.\n');
    }

    // Success summary
    console.log('╔════════════════════════════════════════════════════════════════════╗');
    console.log('║  ✓ STORAGE COMPLETE                                               ║');
    console.log(
      `║  Processed: ${embeddedChunks.length} embedded chunks → ${storedCount} stored  ║`,
    );
    console.log('║  Ready for semantic search and RAG retrieval.                      ║');
    console.log('╚════════════════════════════════════════════════════════════════════╝\n');
  } catch (error) {
    console.error('\n✗ STORAGE FAILED');
    console.error(`✗ ${error.message}\n`);
    process.exit(1);
  }
}

// Self-executing module
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error('\n✗ Fatal error:', err.message);
    process.exit(1);
  });
}
