/**
 * Embedding Storage Script
 *
 * Stores pre-generated embeddings from embedded_chunks.json into Supabase.
 * Reads from backend/datasets/out/embedded_chunks.json (generated by generate_embeddings.js)
 * or from backend/datasets/archives/embedded_chunks.json when run with `--archives`.
 *
 * Usage:
 *   node store_embeddings.js                # Normal mode: store in Supabase
 *   node store_embeddings.js --dry-run      # Dry-run: write to datasets/out/stored_documents.jsonl
 *   node store_embeddings.js --archives     # Archive mode: read/store from datasets/archives/
 *   node store_embeddings.js --archives --dry-run  # Both: write to datasets/archives/stored_documents.jsonl
 *
 * In dry-run mode, documents are written to a local JSONL file instead of Supabase.
 * The output file is maintained as read-only for durability, but is temporarily unlocked
 * during batch writes to allow appending new documents.
 *
 * Uses centralized embedding configuration from backend/src/config/embedding.js
 */

import '#server/bootstrap.js';
import fs from 'fs';
import path from 'path';
import process from 'process';
import { createSupabaseClient } from '#database/supabase.client.js';
import {
  ARCHIVES_EMBEDDED_CHUNKS_JSON,
  EMBEDDED_CHUNKS_JSON,
  STORED_DOCUMENTS_JSONL,
  ARCHIVES_STORED_DOCUMENTS_JSONL,
  prepareWrite,
  ensureDir,
  writeJsonl,
} from '#utils/datasetsUtils.js';
import { BACKEND_CONFIG } from '#config/backend.config.js';
import { isValidTextForEmbedding, isValidEmbedding } from '#config/embedding.js';
import { fileURLToPath } from 'url';

// Determine whether we should target the archive dataset.
// CLI flags take precedence but falling back to environment via BACKEND_CONFIG
const useArchive = process.argv.includes('--archives') || process.argv.includes('--archive');
const DRY_RUN = process.argv.includes('--dry-run') || !BACKEND_CONFIG.supabase.serviceKey;

// Build database config based on archive flag (at module scope for use in multiple functions)
const dbConfig = {
  tables: {
    documents: useArchive ? 'documents_archives' : 'documents',
  },
  functions: {
    truncate: useArchive ? 'truncate_documents_archives' : 'truncate_documents',
  },
};

let supabase = null;
if (!DRY_RUN) {
  supabase = createSupabaseClient();
}

/**
 * Load previously generated embedded chunks
 * @param {string} embeddedChunksPath - Path to embedded_chunks.json
 * @returns {Array} Array of embedded chunk objects
 * @throws {Error} If file not found or invalid JSON
 */
export function loadEmbeddedChunks(embeddedChunksPath) {
  if (!fs.existsSync(embeddedChunksPath)) {
    throw new Error(`Embedded chunks file not found at ${embeddedChunksPath}`);
  }

  try {
    const fileContent = fs.readFileSync(embeddedChunksPath, 'utf-8');
    const chunks = JSON.parse(fileContent);

    if (!Array.isArray(chunks)) {
      throw new Error('Embedded chunks file must contain a JSON array');
    }

    console.log(`✓ Loaded ${chunks.length} embedded chunks from ${embeddedChunksPath}`);
    return chunks;
  } catch (error) {
    throw new Error(`Failed to load embedded chunks: ${error.message}`);
  }
}

/**
 * Store embedded chunks in Supabase documents table
 * @param {Array} embeddedChunks - Chunks with embedding vectors
 * @returns {Promise<number>} Number of documents successfully stored
 * @throws {Error} If storage fails after retries
 */
export async function storeInSupabase(embeddedChunks) {
  console.log(
    `\nStoring ${embeddedChunks.length} documents${DRY_RUN ? ' (dry-run -> local JSONL)' : ' in Supabase'}...`,
  );

  if (!DRY_RUN) {
    const testUrl = `${BACKEND_CONFIG.supabase.url}/rest/v1/documents?select=count`;
    console.log(`📡 Testing raw connection to: ${testUrl}`);

    try {
      const response = await fetch(testUrl, {
        headers: {
          apikey: BACKEND_CONFIG.supabase.serviceKey,
          Authorization: `Bearer ${BACKEND_CONFIG.supabase.serviceKey}`,
        },
      });
      console.log(`✅ Status: ${response.status} ${response.statusText}`);
    } catch (err) {
      console.error('❌ RAW FETCH FAILED');
      console.error('Check: Is there a VPN/Firewall/Proxy active?');
      console.log('Error Cause:', err.cause); // This will tell us if it's ECONNREFUSED or ENOTFOUND
    }
  }

  // Determine target table and function names based on archive flag
  const targetTable = dbConfig.tables.documents;

  if (!DRY_RUN) {
    console.log('  Using SUPABASE_SERVICE_ROLE_KEY (required for RLS bypass)\n');
    console.log(`Truncating existing ${targetTable} table (clear previous run data)...`);

    try {
      if (targetTable === 'documents') {
        const { error: truncateError } = await supabase.rpc(dbConfig.functions.truncate);
        if (truncateError) {
          throw new Error(`Truncate failed: ${truncateError.message}`);
        }
      } else if (targetTable === 'documents_archives') {
        // Try RPC first (if available), otherwise delete all rows via service role
        const { error: truncateError } = await supabase.rpc(dbConfig.functions.truncate);
        if (truncateError) {
          console.log('  RPC truncate not available; using direct delete for ' + targetTable);
          const { error: delErr } = await supabase.from(targetTable).delete().neq('id', '');
          if (delErr) {
            throw new Error(`Failed to clear ${targetTable}: ${delErr.message}`);
          }
        }
      }

      console.log(`✓ ${targetTable} cleared.\n`);
    } catch (error) {
      console.error('✗ Table clear failed:', error.message);
      throw error;
    }
  } else {
    console.log('Dry-run mode: skipping table truncate/clear.\n');
  }

  // Determine output path for dry-run mode
  const dryRunOutputPath = useArchive ? ARCHIVES_STORED_DOCUMENTS_JSONL : STORED_DOCUMENTS_JSONL;

  // if we're in dry-run mode we want to start with a clean file each time
  if (DRY_RUN) {
    await prepareWrite(dryRunOutputPath, { clear: true });
  }

  const SUPABASE_BATCH_SIZE = 10;
  let totalStored = 0;
  let batchNum = 0;

  const totalBatches = Math.ceil(embeddedChunks.length / SUPABASE_BATCH_SIZE);
  console.log(`Total batches to process: ${totalBatches} (batch size: ${SUPABASE_BATCH_SIZE})\n`);

  for (let i = 0; i < embeddedChunks.length; i += SUPABASE_BATCH_SIZE) {
    batchNum++;
    const batch = embeddedChunks.slice(i, Math.min(i + SUPABASE_BATCH_SIZE, embeddedChunks.length));
    const documentsToInsert = [];

    // Prepare documents for insertion
    for (const chunk of batch) {
      // Extract structured columns (no defaults - assume upstream normalization)
      const industryVal = chunk.metadata?.industry ?? null;
      const categoryVal = chunk.metadata?.category ?? null;
      const sourceVal = chunk.metadata?.source ?? null;

      // Build metadata object for JSONB
      const baseMeta = {
        chunk_id: chunk.id,
        source_row: chunk.source_row,
        chunk_index: chunk.chunk_index,
        chunk_type: (chunk.metadata && chunk.metadata.chunk_type) || 'primary',
        source_id: (chunk.metadata && chunk.metadata.source_id) || null,
        fields: (chunk.metadata && chunk.metadata.fields) || {},
        word_count: chunk.word_count,
        scale: (chunk.metadata && chunk.metadata.scale) || null,
        r_strategy: (chunk.metadata && chunk.metadata.r_strategy) || null,
        primary_material: (chunk.metadata && chunk.metadata.primary_material) || null,
        geographic_focus: (chunk.metadata && chunk.metadata.geographic_focus) || null,
      };

      // Doc-level document
      if (chunk.embeddings && chunk.embeddings.doc && isValidEmbedding(chunk.embeddings.doc)) {
        documentsToInsert.push({
          content: chunk.content,
          embedding: chunk.embeddings.doc,
          industry: industryVal,
          category: categoryVal,
          source: sourceVal,
          metadata: { ...baseMeta, field_name: 'doc' },
        });
      }

      // Field-level documents
      const fieldEmb = (chunk.embeddings && chunk.embeddings.fields) || {};
      for (const [fname, vec] of Object.entries(fieldEmb)) {
        if (!vec || !isValidEmbedding(vec)) continue;

        const fieldText =
          (chunk.metadata && chunk.metadata.fields && chunk.metadata.fields[fname]) || '';
        if (!isValidTextForEmbedding(fieldText)) continue;

        documentsToInsert.push({
          content: fieldText,
          embedding: vec,
          industry: industryVal,
          category: categoryVal,
          source: sourceVal,
          metadata: { ...baseMeta, field_name: fname },
        });
      }
    }

    if (documentsToInsert.length === 0) {
      console.log(`  Batch ${batchNum}: No valid documents (all embeddings invalid)`);
      continue;
    }

    // Insert batch with error handling
    if (DRY_RUN) {
      // Ensure output directory exists; file itself has already been prepared
      await ensureDir(path.dirname(dryRunOutputPath));
      try {
        await writeJsonl(dryRunOutputPath, documentsToInsert, {
          append: true,
          // no need to clear here because we cleared before the loop
        });
        totalStored += documentsToInsert.length;
        console.log(
          `  ✔ Batch ${batchNum}/${totalBatches}: Wrote ${documentsToInsert.length} documents (total: ${totalStored}) to ${dryRunOutputPath}`,
        );
      } catch (error) {
        console.error(
          `  ✗ Batch ${batchNum}/${totalBatches}: Failed to write JSONL:`,
          error.message,
        );
        throw error;
      }
    } else {
      try {
        const { data, error } = await supabase.from(targetTable).insert(documentsToInsert).select();

        if (error) {
          throw new Error(`Insert failed: ${error.message}`);
        }

        if (!Array.isArray(data)) {
          throw new Error('Unexpected response: data is not an array');
        }

        totalStored += data.length;
        console.log(
          `  ✔ Batch ${batchNum}/${totalBatches}: Inserted ${data.length} documents (total: ${totalStored}) into ${targetTable} (sample ID: ${data[0]?.id || 'N/A'})`,
        );
      } catch (error) {
        console.error(`  ✗ Batch ${batchNum}/${totalBatches} failed:`, error.message);
        throw error;
      }
    }
  }

  console.log(`\n✓ Successfully stored ${totalStored} documents in Supabase\n`);
  return totalStored;
}

/**
 * Validate stored embeddings with test query
 * @private
 */
async function validateStorage() {
  console.log('\nValidating stored embeddings...');

  try {
    // Count total documents in the target table (dynamic based on archive flag)
    try {
      const { count, error: countErr } = await supabase
        .from(dbConfig.tables.documents)
        .select('id', { head: true, count: 'exact' });
      if (!countErr) {
        console.log(`  ✓ Total documents in ${dbConfig.tables.documents}: ${count}`);
      }
    } catch (e) {
      console.warn('  ⚠️️ Could not retrieve documents count:', e.message);
    }

    // Test vector search with a dummy embedding
    const testEmbedding = Array(1536).fill(0.1);
    const searchResult = await supabase.rpc(dbConfig.functions.match_documents, {
      query_embedding: testEmbedding,
      match_count: 1,
    });

    if (!searchResult.error) {
      console.log(`  ✓ Vector search function operational`);
      if (searchResult.data && searchResult.data.length > 0) {
        console.log(`  ✓ Search returned ${searchResult.data.length} result(s)`);
      }
    }
  } catch (error) {
    console.warn('  ⚠️️ Validation warning:', error.message);
  }
}

/**
 * Main execution pipeline
 * @async
 */
export async function main() {
  const embeddedChunksPath = useArchive ? ARCHIVES_EMBEDDED_CHUNKS_JSON : EMBEDDED_CHUNKS_JSON;

  try {
    console.log('╔════════════════════════════════════════════════════════════════════╗');
    console.log('║  Embedding Storage Pipeline                                        ║');
    console.log('║  Circular Economy Business Auditor                                 ║');
    console.log('╚════════════════════════════════════════════════════════════════════╝\n');

    // Step 1: Load embedded chunks
    const embeddedChunks = loadEmbeddedChunks(embeddedChunksPath);

    // Step 2: Store in Supabase
    const storedCount = await storeInSupabase(embeddedChunks);

    // Step 3: Validate storage (production only)
    if (!DRY_RUN) {
      await validateStorage();
    } else {
      console.log('Dry-run mode: skipped Supabase validation.\n');
    }

    // Success summary
    console.log('╔════════════════════════════════════════════════════════════════════╗');
    console.log('║  ✓ STORAGE COMPLETE                                               ║');
    console.log(
      `║  Processed: ${embeddedChunks.length} embedded chunks → ${storedCount} stored  ║`,
    );
    console.log('║  Ready for semantic search and RAG retrieval.                      ║');
    console.log('╚════════════════════════════════════════════════════════════════════╝\n');
  } catch (error) {
    console.error('\n✗ STORAGE FAILED');
    console.error(`✗ ${error.message}\n`);
    process.exit(1);
  }
}

// Self-executing module
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error('\n✗ Fatal error:', err.message);
    process.exit(1);
  });
}
