import { RadioTower, Coins, Recycle } from 'lucide-react';

// Shared group style configuration for parameter-themed UI (icons + Tailwind classes)
export const GROUP_STYLE_CONFIG = {
  'Access Value': {
    Icon: RadioTower,
    iconColor: 'text-violet-500',
    headerBg: 'bg-violet-100',
    headerIconColor: 'text-violet-500',
    subtitle: 'Reach and participation across stakeholders',
    paramBg: 'bg-violet-50',
    paramTextColor: 'text-violet-700',
    panelBg: 'bg-violet-50',
    panelBorder: 'border-violet-200',
    panelTitle: 'text-violet-700',
    panelItemBorder: 'border-violet-400',
    badgeBg: 'bg-violet-100',
    badgeBorder: 'border-violet-300',
    badgeText: 'text-violet-700',
    panelItemText: 'text-violet-900',
  },
  'Embedded Value': {
    Icon: Coins,
    iconColor: 'text-emerald-500',
    headerBg: 'bg-emerald-100',
    headerIconColor: 'text-emerald-600',
    subtitle: 'Intrinsic worth retained within the system',
    paramBg: 'bg-emerald-50',
    paramTextColor: 'text-emerald-700',
    panelBg: 'bg-emerald-50',
    panelBorder: 'border-emerald-200',
    panelTitle: 'text-emerald-700',
    panelItemBorder: 'border-emerald-400',
    badgeBg: 'bg-emerald-100',
    badgeBorder: 'border-emerald-300',
    badgeText: 'text-emerald-700',
    panelItemText: 'text-emerald-900',
  },
  'Processing Value': {
    Icon: Recycle,
    iconColor: 'text-amber-500',
    headerBg: 'bg-amber-100/50',
    headerIconColor: 'text-amber-500',
    subtitle: 'Efficiency and safety of circularity processes',
    paramBg: 'bg-amber-100/50',
    paramTextColor: 'text-amber-700',
    panelBg: 'bg-amber-50',
    panelBorder: 'border-amber-200',
    panelTitle: 'text-amber-700',
    panelItemBorder: 'border-amber-400',
    badgeBg: 'bg-amber-100',
    badgeBorder: 'border-amber-300',
    badgeText: 'text-amber-700',
    panelItemText: 'text-amber-900',
  },
};

export const DEFAULT_CONFIG = {
  Icon: Coins,
  iconColor: 'text-slate-400',
  headerBg: 'bg-slate-50',
  headerIconColor: 'text-slate-400',
  subtitle: '',
  paramBg: 'bg-slate-50',
  paramTextColor: 'text-slate-700',
  panelBg: 'bg-slate-50',
  panelBorder: 'border-slate-200',
  panelTitle: 'text-slate-700',
  panelItemBorder: 'border-slate-200',
  badgeBg: 'bg-slate-50',
  badgeBorder: 'border-slate-200',
  badgeText: 'text-slate-700',
  panelItemText: 'text-slate-800',
};
