import { Coins, RadioTower, Recycle } from 'lucide-react';

// Shared group style configuration for parameter-themed UI (icons + Tailwind classes)
export const GROUP_STYLE_CONFIG = {
  'Access Value': {
    Icon: RadioTower,
    iconColor: 'text-[var(--accent)]',
    headerBg: 'bg-[var(--accent-soft)]',
    headerIconColor: 'text-[var(--accent)]',
    subtitle: 'Reach and participation across stakeholders',
    paramBg: 'bg-[var(--accent-soft)]',
    paramTextColor: 'text-[var(--accent-soft-fg)]',
    panelBg: 'bg-[var(--accent-soft)]',
    panelBorder: 'border-[var(--border)]',
    panelTitle: 'text-[var(--accent-soft-fg)]',
    panelItemBorder: 'border-[var(--accent)]',
    badgeBg: 'bg-[var(--accent-soft)]',
    badgeBorder: 'border-[var(--accent)]',
    badgeText: 'text-[var(--accent-soft-fg)]',
    panelItemText: 'text-[var(--foreground)]',
  },
  'Embedded Value': {
    Icon: Coins,
    iconColor: 'text-[var(--success)]',
    headerBg: 'bg-[var(--success-soft)]',
    headerIconColor: 'text-[var(--success)]',
    subtitle: 'Intrinsic worth retained within the system',
    paramBg: 'bg-[var(--success-soft)]',
    paramTextColor: 'text-[var(--success)]',
    panelBg: 'bg-[var(--success-soft)]',
    panelBorder: 'border-[var(--success)]',
    panelTitle: 'text-[var(--success)]',
    panelItemBorder: 'border-[var(--success)]',
    badgeBg: 'bg-[var(--success-soft)]',
    badgeBorder: 'border-[var(--success)]',
    badgeText: 'text-[var(--success)]',
    panelItemText: 'text-[var(--foreground)]',
  },
  'Processing Value': {
    Icon: Recycle,
    iconColor: 'text-[var(--warning)]',
    headerBg: 'bg-[var(--warning-soft)]',
    headerIconColor: 'text-[var(--warning)]',
    subtitle: 'Efficiency and safety of circularity processes',
    paramBg: 'bg-[var(--warning-soft)]',
    paramTextColor: 'text-[var(--warning)]',
    panelBg: 'bg-[var(--warning-soft)]',
    panelBorder: 'border-[var(--warning)]',
    panelTitle: 'text-[var(--warning)]',
    panelItemBorder: 'border-[var(--warning)]',
    badgeBg: 'bg-[var(--warning-soft)]',
    badgeBorder: 'border-[var(--warning)]',
    badgeText: 'text-[var(--warning)]',
    panelItemText: 'text-[var(--foreground)]',
  },
};

export const DEFAULT_CONFIG = {
  Icon: Coins,
  iconColor: 'text-[var(--muted)]',
  headerBg: 'bg-[var(--surface)]',
  headerIconColor: 'text-[var(--muted)]',
  subtitle: '',
  paramBg: 'bg-[var(--surface)]',
  paramTextColor: 'text-[var(--foreground)]',
  panelBg: 'bg-[var(--surface)]',
  panelBorder: 'border-[var(--border)]',
  panelTitle: 'text-[var(--foreground)]',
  panelItemBorder: 'border-[var(--border)]',
  badgeBg: 'bg-[var(--surface)]',
  badgeBorder: 'border-[var(--border)]',
  badgeText: 'text-[var(--foreground)]',
  panelItemText: 'text-[var(--foreground)]',
};
