#!/usr/bin/env sh

echo "⫸ Checking builds in all workspaces..."
npm run build || { echo "✕ Build failed! Check your code before pushing."; exit 1; }

echo "⫸ Running test suites..."
npm test || { echo "✕ Tests failed! Push aborted."; exit 1; }

echo "✓ Everything looks good. Pushing now..."
